version: "3.8"
services:
  dbsql:
    image: postgres:13.1-alpine
    container_name: postgres_db_container
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - dbSqlNetwork
    volumes:
      - pg_data:/var/lib/postgresql/data/
networks:
  dbSqlNetwork:
    driver: bridge
volumes:
  pg_data:
